# WORKAROUND:
# 1. minikube ssh
# 2. sudo chown -R 1000 /mnt/data/
# 3. exit

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/"
